server:
  port: 8080
spring:
  profiles:
    active: dev
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/spring-tutorial-db?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: dev
welcome:
  message: Hello World, This is developer profile!
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/spring-tutorial-db-qa?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: qa
welcome:
  message: Hello World, This is qa profile!

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/spring-tutorial-db-prod?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: prod
welcome:
  message: Hello World, This is production profile!
